Data Analytics
iron-claw-972/FRC2025 pull request #6
Opened 2024-11-13 23:48 UTC by johaj10

## Overview

This PR will improve our Data Analytics system by adding our new logging API. Our existing LogManager

## Design Doc

No design doc.

## Tests Ran

Code builds, runs in sim, and runs on the robot.

## Additional Notes

Requires dependency of DogLog as a vendor dep. Vendor dep JSON included in this PR.

2024-11-14 02:28 UTC, Kyle-Eldridge requested changes
Mostly small changes and questinns, but a few bigger changes like using LogLevel.

2024-11-14 02:28 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/Robot.java
> +        // LogManager.logSupplier("Test/Value2", () -> 8, 2, 5);
Remove these.

2024-11-14 02:28 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/Robot.java
> +        // LogManager.log("Test/Value1", 3, 1, 2);
This one too.

2024-11-14 02:28 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/constants/Constants.java
> +    public static final LogLevel LOG_LEVEL = LogLevel.DEBUG;
You could keep the current code, although it might be better to have a LogLevel.NONE instead of a separate boolean to disable it.

2024-11-14 02:28 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/util/LogManager.java
> +public class LogManager extends DogLog {
The name of the branch is clawLog. Do you plan to leave this as LogManager or rename it to ClawLog?

2024-11-14 02:28 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/util/LogManager.java
> +    }
It should be < and >, not <= and >=. Also, maybe log the value that was out of range in addition tot he name.

2024-11-14 02:28 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/util/LogManager.java
> +    NONE
You have this enum but don't use it. When logging something, you should pass in a log type or use a default log type. Methods in this class should only log it if it is greater than or equal to the log type in Constants.

2024-11-20 03:38 UTC, Kyle-Eldridge approved these changes

2024-11-21 00:31 UTC, johaj10 commented
We've addressed all of the issues. I also have added the logs folder to the gitignore, so log data generated from simulation isn't added to the repository.

2024-11-21 00:33 UTC, johaj10 commented
@chem7397 Would you be able to review this pull request? It would be great to get your input! Thanks!

2024-11-28 12:29 UTC, chem7397 approved these changes

2024-11-29 05:09 UTC, merged